# Generated by Django 4.2.1 on 2023-05-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joriking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='joriking/image/%Y/%m/%d')),
                ('pred_path', models.CharField(max_length=255)),
                ('ingredients', models.CharField(max_length=255)),
            ],
        ),
    ]
